// Offline generator: validates fixture documents and writes SQL, never connects to a database.
const fs = require('node:fs')
const path = require('node:path')
const vm = require('node:vm')
const ts = require('typescript')
const root = path.resolve(__dirname, '../../..')
const cache = new Map()
function loadSource(relative) {
  const filename = path.join(root, relative)
  if (cache.has(filename)) return cache.get(filename)
  const module = { exports: {} }
  const output = ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText
  const localRequire = name => name.startsWith('@/') ? loadSource(name.slice(2) + '.ts') : require(name)
  vm.runInNewContext(output, { module, exports: module.exports, require: localRequire }, { filename })
  cache.set(filename, module.exports)
  return module.exports
}
const { programDocumentSchema } = loadSource('lib/programs/content.ts')
const { editorialDemoDocuments } = loadSource('data/programs/editorial-demo-documents.ts')
const { serviceDemoDocument } = loadSource('data/programs/service-demo-document.ts')
const definitions = [
  ['test-aac-support', 'warm', serviceDemoDocument],
  ['test-community-outreach', 'energetic', editorialDemoDocuments.outreach],
  ['test-deessa-companion', 'editorial', editorialDemoDocuments.research],
  ['test-1000-families', 'campaign', editorialDemoDocuments.campaign],
]
const fixtures = definitions.map(([slug, theme, document]) => {
  const parsed = programDocumentSchema.parse(JSON.parse(JSON.stringify(document)))
  const ids = parsed.sections.map(section => section.id)
  if (new Set(ids).size !== ids.length) throw new Error(`Duplicate section IDs in ${slug}`)
  const actions = [...parsed.hero.actions, ...parsed.sections.flatMap(section => section.content.type === 'cta' ? section.content.buttons : [])]
  for (const action of actions) if (action.url.startsWith('#') && !ids.includes(action.url.slice(1))) throw new Error(`Missing anchor ${action.url} in ${slug}`)
  parsed.seo = { title: parsed.title + ' — Test fixture', description: parsed.shortDescription }
  return { slug, theme, document: parsed }
})
const payload = JSON.stringify(fixtures, null, 2)
if (payload.includes('$fixtures$') || payload.includes('$seed$')) throw new Error('SQL delimiter in fixture content')
const sql = `-- Programs CMS editorial test fixtures (P07, optional development seed).
-- Generated by: node scripts/db/programs-migrations/generate-p07.cjs
-- Run P01-P06 and P08-P10 first; P10 enables the canonical CMS hero format.
-- Development/staging only. All four programs remain drafts.
-- RESET: deletes the four exact test slugs below, including published/archived copies.
-- Their drafts, publications, versions, sections, asset metadata and publish requests
-- are removed. Recreated programs have new IDs and draft revision 1.
-- Storage files are not deleted. Other programs are not changed.
-- The entire reset rolls back if any delete or insert fails.

begin;
do $seed$
declare
  fixture jsonb;
  doc jsonb;
  program_id uuid;
  old_program_id uuid;
  admin_id uuid;
begin
  if exists (
    select 1 from pg_constraint
    where conrelid = 'public.program_drafts'::regclass
      and conname = 'program_drafts_hero_valid'
      and position('imageAlt' in pg_get_constraintdef(oid)) > 0
  ) then
    raise exception 'Apply P10-fix-program-drafts-hero-constraint.sql before running P07.';
  end if;

  select user_id into admin_id from public.admin_users
    where is_active = true order by user_id limit 1;

  for fixture in select value from jsonb_array_elements($fixtures$
${payload}
$fixtures$::jsonb)
  loop
    doc := fixture->'document';
    -- Only the exact slug in this four-fixture payload is eligible for deletion.
    select existing.id into old_program_id from public.programs existing
      where existing.slug = fixture->>'slug' for update;
    if old_program_id is not null then
      -- Remove references to version snapshots before cascading the program delete.
      delete from public.program_publications where program_publications.program_id = old_program_id;
      delete from public.program_publish_requests where program_publish_requests.program_id = old_program_id;
      delete from public.programs where id = old_program_id;
    end if;

    insert into public.programs
      (slug, title, category, theme, eyebrow, short_description, tags, status, created_by, updated_by)
    values (
      fixture->>'slug', doc->>'title', doc->>'category', fixture->>'theme',
      doc->>'eyebrow', doc->>'shortDescription',
      array(select jsonb_array_elements_text(doc->'tags')), 'draft', admin_id, admin_id
    )
    returning id into program_id;

    insert into public.program_drafts
      (program_id, schema_version, hero, sections, seo_title, seo_description, revision, updated_by)
    values (
      program_id, 1, doc->'hero', doc->'sections',
      doc->'seo'->>'title', doc->'seo'->>'description', 1, admin_id
    );

    raise notice 'Ready: % (% sections), admin preview /admin/programs/%/preview',
      fixture->>'slug', jsonb_array_length(doc->'sections'), program_id;
  end loop;
end;
$seed$;
commit;

-- Open each draft from /admin/programs, edit/save, and use Preview.
-- /whatwedo/test-... becomes available only after publishing through the admin.
`
const destination = path.join(__dirname, 'P07-programs-test-fixtures.sql')
if (process.argv.includes('--check')) {
  if (fs.readFileSync(destination, 'utf8').replace(/\r\n/g, '\n') !== sql) throw new Error('P07 is out of date; rerun this generator without --check')
} else fs.writeFileSync(destination, sql, 'utf8')
console.log(`P07 ${process.argv.includes('--check') ? 'verified' : 'generated'}: ${fixtures.map(f => f.document.category + ' (' + f.document.sections.length + ' sections)').join(', ')}`)
