-- Programs CMS editorial test fixtures (P07, optional development seed).
-- Generated by: node scripts/db/programs-migrations/generate-p07.cjs
-- Run P01-P06 and P08-P10 first; P10 enables the canonical CMS hero format.
-- Development/staging only. All four programs remain drafts.
-- RESET: deletes the four exact test slugs below, including published/archived copies.
-- Their drafts, publications, versions, sections, asset metadata and publish requests
-- are removed. Recreated programs have new IDs and draft revision 1.
-- Storage files are not deleted. Other programs are not changed.
-- The entire reset rolls back if any delete or insert fails.

begin;
do $seed$
declare
  fixture jsonb;
  doc jsonb;
  program_id uuid;
  old_program_id uuid;
  admin_id uuid;
begin
  if exists (
    select 1 from pg_constraint
    where conrelid = 'public.program_drafts'::regclass
      and conname = 'program_drafts_hero_valid'
      and position('imageAlt' in pg_get_constraintdef(oid)) > 0
  ) then
    raise exception 'Apply P10-fix-program-drafts-hero-constraint.sql before running P07.';
  end if;

  select user_id into admin_id from public.admin_users
    where is_active = true order by user_id limit 1;

  for fixture in select value from jsonb_array_elements($fixtures$
[
  {
    "slug": "test-aac-support",
    "theme": "warm",
    "document": {
      "schemaVersion": 1,
      "title": "AAC Support Services",
      "shortDescription": "Communication support that helps families discover tools, confidence and connections.",
      "eyebrow": "SERVICES & PROGRAMS",
      "category": "service",
      "tags": [
        "communication",
        "aac",
        "families",
        "support"
      ],
      "hero": {
        "title": "Every little expression. A big possibility.",
        "description": "Communication looks different for every child. We help families discover the tools, confidence and connections to find their own way.",
        "image": {
          "url": "/twins-together.jpg",
          "alt": "Two children sharing a moment outdoors; illustrative photograph"
        },
        "actions": [
          {
            "label": "Find support for your family",
            "url": "#support",
            "variant": "primary"
          },
          {
            "label": "Explore the program",
            "url": "#about",
            "variant": "secondary"
          }
        ],
        "note": {
          "icon": "Heart",
          "text": "At your pace. By your side."
        },
        "sticker": {
          "icon": "Sparkles",
          "text": "Every mind is a gift."
        },
        "photoNote": "A connection can begin with the smallest moment."
      },
      "seo": {
        "title": "AAC Support Services — Test fixture",
        "description": "Communication support that helps families discover tools, confidence and connections."
      },
      "sections": [
        {
          "id": "facts",
          "enabled": true,
          "content": {
            "type": "facts_bar",
            "facts": [
              {
                "label": "THE PROGRAM",
                "value": "AAC communication support"
              },
              {
                "label": "WHO IT’S FOR",
                "value": "Children & their families"
              },
              {
                "label": "WHERE WE CONNECT",
                "value": "Lalitpur + online"
              },
              {
                "label": "OUR APPROACH",
                "value": "Family-centered, always"
              }
            ]
          }
        },
        {
          "id": "about",
          "heading": "A LITTLE UNDERSTANDING GOES A LONG WAY",
          "intro": "More ways to say “this is me.”",
          "description": "AAC means augmentative and alternative communication. It can be a picture, a gesture or a digital tool. What matters is finding what feels right for your child.",
          "enabled": true,
          "content": {
            "type": "features",
            "layout": "grid",
            "features": [
              {
                "title": "A way to express themselves",
                "description": "From picture cards to communication boards, we explore tools that fit your child’s everyday life.",
                "icon": "💬"
              },
              {
                "title": "Confidence for your family",
                "description": "Practical, gentle guidance for parents and caregivers. Small things to try, at your own pace.",
                "icon": "♡"
              },
              {
                "title": "Connection beyond home",
                "description": "Work with educators and a community of families to make communication part of every day.",
                "icon": "👥"
              }
            ]
          }
        },
        {
          "id": "journey",
          "heading": "NO TWO JOURNEYS ARE THE SAME",
          "intro": "We start where you are.",
          "description": "You don’t need all the answers before reaching out. We’ll figure out the next step together.",
          "enabled": true,
          "content": {
            "type": "how_it_works",
            "items": [
              {
                "title": "Let’s have a conversation",
                "description": "Tell us about your child, your everyday routines and what you hope for."
              },
              {
                "title": "Find what works together",
                "description": "Explore communication tools and build a plan around your family."
              },
              {
                "title": "Practice, learn, celebrate",
                "description": "Try small steps at home, with regular check-ins and encouragement."
              }
            ],
            "handwrittenNote": "Small steps count, too."
          }
        },
        {
          "id": "family-story",
          "heading": "THE MOMENTS THAT MATTER",
          "enabled": true,
          "content": {
            "type": "story",
            "quote": "It wasn’t just a new way to communicate. It was a new way to connect.",
            "description": "A sample family story about finding everyday moments of understanding through a simple picture board.",
            "person": "A parent’s perspective",
            "role": "Illustrative story",
            "location": "Lalitpur",
            "image": {
              "url": "/deessa-resources/IMG_8102.JPG",
              "alt": "Two children together near bookshelves; illustrative photograph"
            },
            "stats": [
              {
                "value": "120",
                "label": "families learning together"
              },
              {
                "value": "24",
                "label": "community sessions"
              }
            ]
          }
        },
        {
          "id": "support",
          "heading": "LET’S MAKE THE FIRST STEP EASIER",
          "intro": "A few things you might wonder.",
          "description": "Every family’s questions are welcome.",
          "enabled": true,
          "content": {
            "type": "faq",
            "items": [
              {
                "question": "Who is this program for?",
                "answer": "In this sample program, children aged 2–12 and their parents or caregivers can explore communication support together."
              },
              {
                "question": "Do we need a diagnosis to ask for help?",
                "answer": "For this prototype, families can start with a conversation. A real program would show its referral and eligibility requirements here."
              },
              {
                "question": "Where do sessions take place?",
                "answer": "Sample delivery: in-person sessions in Lalitpur, with online follow-ups for families further away."
              },
              {
                "question": "What does support cost?",
                "answer": "Sample model: an initial conversation at no cost, with subsidized support options discussed individually."
              }
            ]
          }
        },
        {
          "id": "enquire",
          "heading": "YOU DON’T HAVE TO FIGURE IT OUT ALONE",
          "enabled": true,
          "content": {
            "type": "cta",
            "title": "Let’s find your next small step.",
            "description": "Start with a conversation about your family and the support you’re looking for.",
            "buttons": [
              {
                "label": "Ask about communication support",
                "url": "/contact",
                "variant": "primary"
              }
            ]
          }
        },
        {
          "id": "service-metrics",
          "heading": "SMALL STEPS, SHARED PROGRESS",
          "intro": "Every connection counts.",
          "description": "Illustrative program metrics for testing the service layout.",
          "enabled": true,
          "content": {
            "type": "stats",
            "stats": [
              {
                "value": "120",
                "label": "families learning together"
              },
              {
                "value": "24",
                "label": "community sessions"
              },
              {
                "value": "12",
                "label": "local educators"
              },
              {
                "value": "3",
                "label": "ways to connect"
              }
            ]
          }
        },
        {
          "id": "service-gallery",
          "heading": "EVERYDAY CONNECTIONS",
          "intro": "A little glimpse of together.",
          "description": "Illustrative photographs for the service gallery.",
          "enabled": true,
          "content": {
            "type": "gallery",
            "layout": "grid",
            "images": [
              {
                "url": "/twins-together.jpg",
                "alt": "Two children sharing a moment outdoors; illustrative photograph",
                "caption": "A moment of connection."
              },
              {
                "url": "/deessa-resources/IMG_8102.JPG",
                "alt": "Two children together near bookshelves; illustrative photograph",
                "caption": "Learning alongside each other."
              },
              {
                "url": "/twins-together.jpg",
                "alt": "Two children sharing a moment outdoors; illustrative photograph",
                "caption": "Every expression matters."
              },
              {
                "url": "/deessa-resources/IMG_8102.JPG",
                "alt": "Two children together near bookshelves; illustrative photograph",
                "caption": "Small steps, together."
              }
            ]
          }
        }
      ],
      "relatedProgramIds": []
    }
  },
  {
    "slug": "test-community-outreach",
    "theme": "energetic",
    "document": {
      "schemaVersion": 1,
      "title": "Community Connection Series",
      "shortDescription": "A community learning journey. Three places. Many perspectives. A little more understanding.",
      "eyebrow": "COMMUNITY & OUTREACH / FIELD JOURNAL 01",
      "category": "outreach",
      "tags": [],
      "hero": {
        "title": "Good things",
        "description": "happen *together.*",
        "image": {
          "url": "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1600&q=85",
          "alt": "Friends gathered outdoors; illustrative photograph"
        },
        "actions": [],
        "photoNote": "A community learning journey.\nThree places. Many perspectives.\nA little more understanding.",
        "editorial": {
          "stamp": "LISTEN.\nLEARN.\nCONNECT.",
          "location": "Across the Kathmandu Valley",
          "captionLeft": "THE COMMUNITY CONNECTION SERIES",
          "captionRight": "APRIL 2026 · SAMPLE JOURNAL"
        }
      },
      "seo": {
        "title": "Community Connection Series — Test fixture",
        "description": "A community learning journey. Three places. Many perspectives. A little more understanding."
      },
      "sections": [
        {
          "id": "ribbon",
          "heading": "",
          "intro": "",
          "presentation": "ribbon",
          "enabled": true,
          "content": {
            "type": "stats",
            "stats": [
              {
                "value": "140",
                "label": "people connected"
              },
              {
                "value": "3",
                "label": "communities"
              },
              {
                "value": "1",
                "label": "shared conversation"
              }
            ]
          }
        },
        {
          "id": "opening",
          "heading": "IT STARTS WITH SHOWING UP",
          "intro": "Not a lecture.\nA conversation.",
          "enabled": true,
          "content": {
            "type": "rich_text",
            "body": "<p>We brought families, teachers and local volunteers into the same space. To listen first. To try something new. To turn “I’m not sure” into “let’s find out together.”</p><p>Through hands-on activities and honest conversations, our sample outreach series explores what inclusion can look like in everyday community life.</p>"
          }
        },
        {
          "id": "field-notes",
          "heading": "POSTCARDS FROM THE JOURNEY",
          "intro": "Different places. Shared hopes.",
          "enabled": true,
          "content": {
            "type": "activities",
            "activities": [
              {
                "place": "Lalitpur",
                "date": "12 April",
                "title": "A space to listen",
                "description": "Parents and educators shared everyday experiences, asked questions and found common ground.",
                "count": "45 participants"
              },
              {
                "place": "Bhaktapur",
                "date": "19 April",
                "title": "Learning by doing",
                "description": "A hands-on afternoon making visual schedules, trying communication cards and swapping ideas.",
                "count": "38 participants"
              },
              {
                "place": "Kavrepalanchok",
                "date": "26 April",
                "title": "Taking the ideas home",
                "description": "Community volunteers helped families turn workshop ideas into small, practical next steps.",
                "count": "57 participants"
              }
            ]
          }
        },
        {
          "id": "photo-essay",
          "heading": "THE LITTLE MOMENTS IN BETWEEN",
          "intro": "Learning looks like this.",
          "description": "Making, sharing, asking, laughing. A photo story brings the experience into focus. Images here are illustrative.",
          "enabled": true,
          "content": {
            "type": "gallery",
            "layout": "story",
            "images": [
              {
                "url": "https://images.unsplash.com/photo-1529390079861-591de354faf5?w=1200&q=85",
                "alt": "Children learning together; illustrative photograph",
                "caption": "Space for curiosity. Space for questions."
              },
              {
                "url": "/deessa-resources/IMG_8102.JPG",
                "alt": "Two children together near bookshelves; illustrative photograph",
                "caption": "Connection is where understanding begins."
              }
            ]
          }
        },
        {
          "id": "community-voices",
          "heading": "COMMUNITY VOICES",
          "intro": "",
          "enabled": true,
          "content": {
            "type": "quote",
            "quote": "“We came with questions.\nWe left with ideas —\n*and each other.”*",
            "person": "A community participant",
            "role": "Sample story"
          }
        },
        {
          "id": "host",
          "heading": "LET’S KEEP THE CONVERSATION GOING",
          "intro": "",
          "enabled": true,
          "content": {
            "type": "cta",
            "title": "Your community.\nOur next chapter?",
            "description": "Bring a learning session to your school, neighborhood or community group.",
            "buttons": [
              {
                "label": "Explore hosting a session",
                "url": "/contact",
                "variant": "primary"
              }
            ]
          }
        },
        {
          "id": "outreach-metrics",
          "heading": "BY THE NUMBERS",
          "intro": "A journey you can feel.",
          "description": "A simple impact block gives the field journal a clear sense of reach without losing the human stories.",
          "presentation": "auto",
          "enabled": true,
          "content": {
            "type": "stats",
            "stats": [
              {
                "value": "140",
                "label": "people connected"
              },
              {
                "value": "3",
                "label": "communities visited"
              },
              {
                "value": "9",
                "label": "local facilitators"
              },
              {
                "value": "12h",
                "label": "shared conversation"
              }
            ]
          }
        },
        {
          "id": "outreach-gallery",
          "heading": "FIELD NOTES / VISUAL EDITION",
          "intro": "The details tell the story.",
          "description": "The gallery can grow with each outreach stop, giving the admin team a flexible way to publish a living journal.",
          "presentation": "auto",
          "enabled": true,
          "content": {
            "type": "gallery",
            "layout": "grid",
            "images": [
              {
                "url": "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1600&q=85",
                "alt": "Friends gathered outdoors; illustrative photograph",
                "caption": "Arriving with curiosity."
              },
              {
                "url": "https://images.unsplash.com/photo-1529390079861-591de354faf5?w=1200&q=85",
                "alt": "Children learning together; illustrative photograph",
                "caption": "Making space to try."
              },
              {
                "url": "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=1800&q=85",
                "alt": "Hands gathered together; illustrative photograph",
                "caption": "Working things out together."
              },
              {
                "url": "/deessa-resources/IMG_8102.JPG",
                "alt": "Two children together near bookshelves; illustrative photograph",
                "caption": "Taking the idea home."
              }
            ]
          }
        }
      ],
      "relatedProgramIds": []
    }
  },
  {
    "slug": "test-deessa-companion",
    "theme": "editorial",
    "document": {
      "schemaVersion": 1,
      "title": "deessa Companion",
      "shortDescription": "Meet deessa Companion. An exploration of simple digital tools that support communication, routines and everyday independence.",
      "eyebrow": "RESEARCH & INNOVATION",
      "category": "research",
      "tags": [
        "Accessible by design",
        "Family-informed",
        "Locally grounded"
      ],
      "hero": {
        "title": "Designed for\nthe everyday.",
        "description": "Built around you.",
        "actions": [
          {
            "label": "Explore the concept",
            "url": "#interactive-concept",
            "variant": "primary"
          },
          {
            "label": "Our approach",
            "url": "#approach",
            "variant": "secondary"
          }
        ],
        "editorial": {
          "status": "CONCEPT / IN EXPLORATION",
          "conceptLabel": "THE EVERYDAY TOOLKIT",
          "conceptTitle": "A little clarity.\nA little confidence.",
          "conceptRoutine1": "A morning routine, made yours.",
          "conceptRoutine2": "A new way to say what you need.",
          "conceptBrand": "companion",
          "conceptCredit": "by deessa",
          "figureLabel": "FIG. 01 — SMALL TOOLS, EVERYDAY POSSIBILITIES"
        }
      },
      "seo": {
        "title": "deessa Companion — Test fixture",
        "description": "Meet deessa Companion. An exploration of simple digital tools that support communication, routines and everyday independence."
      },
      "sections": [
        {
          "id": "question",
          "heading": "THE QUESTION",
          "intro": "",
          "presentation": "question",
          "enabled": true,
          "content": {
            "type": "rich_text",
            "body": "<p>How might a simple tool make everyday expression a little easier?</p>"
          }
        },
        {
          "id": "approach",
          "heading": "DESIGNING WITH, NOT JUST FOR",
          "intro": "An idea shaped by listening.",
          "description": "Useful tools begin with real life. Our sample research process puts families’ experiences at the center, from the first question to the next iteration.",
          "enabled": true,
          "content": {
            "type": "how_it_works",
            "items": [
              {
                "title": "Start with everyday life",
                "description": "Conversations with families reveal the moments where a simple tool could make a difference.",
                "date": "01 / LISTEN"
              },
              {
                "title": "Build something small",
                "description": "Co-design simple boards and routines, using familiar symbols and room for personal choices.",
                "date": "02 / MAKE"
              },
              {
                "title": "Test, reflect, improve",
                "description": "Invite feedback, notice what gets in the way and bring those lessons into the next version.",
                "date": "03 / LEARN"
              }
            ]
          }
        },
        {
          "id": "interactive-concept",
          "heading": "LESS EXPLAINING. MORE EXPLORING.",
          "intro": "A small window\ninto the idea.",
          "description": "Tap a few cards and build a phrase. This simplified communication board shows how a familiar, visual interface could help someone express a choice.",
          "enabled": true,
          "content": {
            "type": "built_in_demo",
            "component": "communication_board",
            "checklist": [
              "Clear words paired with familiar symbols",
              "Generous touch targets and calm colors",
              "Space to explore without getting it wrong"
            ],
            "footnote": "Interactive design study. Not the released Companion app."
          }
        },
        {
          "id": "insights",
          "heading": "WHAT WE’RE LEARNING",
          "intro": "The next version\nstarts with a question.",
          "footnote": "Illustrative research themes, not published study findings.",
          "enabled": true,
          "content": {
            "type": "features",
            "layout": "list",
            "features": [
              {
                "title": "Familiarity comes first.",
                "description": "Everyday words and recognizable symbols can make the first interaction feel less demanding."
              },
              {
                "title": "Flexibility matters.",
                "description": "Different routines, languages and preferences call for tools that can grow with a person."
              }
            ]
          }
        },
        {
          "id": "resources",
          "heading": "OPEN NOTEBOOK",
          "intro": "Explore the thinking.",
          "enabled": true,
          "content": {
            "type": "faq",
            "items": [
              {
                "question": "Design brief / A calmer everyday experience",
                "answer": "This concept explores communication cards and visual routines in a simple, accessible interface. The next step would be co-design sessions with families and educators."
              },
              {
                "question": "Accessibility notes / Clear, flexible, familiar",
                "answer": "The prototype uses labeled controls, keyboard interaction, visible focus states and large touch targets. A production tool would also need usability testing with its intended users."
              },
              {
                "question": "Research roadmap / From questions to learning",
                "answer": "Sample roadmap: listen to families, build a small prototype, run supported trials, document feedback and refine. No study results are represented here."
              }
            ]
          }
        },
        {
          "id": "collaborate",
          "heading": "BETTER QUESTIONS. BETTER POSSIBILITIES.",
          "intro": "",
          "enabled": true,
          "content": {
            "type": "cta",
            "title": "Help shape what comes next.",
            "description": "Families, educators, researchers and thoughtful collaborators: there’s a place for your perspective.",
            "buttons": [
              {
                "label": "Explore a collaboration",
                "url": "/contact",
                "variant": "primary"
              }
            ]
          }
        },
        {
          "id": "research-metrics",
          "heading": "EARLY RESULTS / SAMPLE ONLY",
          "intro": "Learning that shapes the next version.",
          "description": "A results area can make the research journey legible while separating exploratory metrics from published findings.",
          "enabled": true,
          "content": {
            "type": "stats",
            "stats": [
              {
                "value": "3",
                "label": "prototype rounds"
              },
              {
                "value": "18",
                "label": "design conversations"
              },
              {
                "value": "6",
                "label": "everyday routines mapped"
              },
              {
                "value": "100%",
                "label": "questions still welcome"
              }
            ]
          }
        },
        {
          "id": "research-gallery",
          "heading": "RESEARCH ARTEFACTS",
          "intro": "Ideas you can see and try.",
          "description": "A visual evidence section can hold prototype snapshots, workshop notes or short videos once the research is live.",
          "enabled": true,
          "content": {
            "type": "gallery",
            "layout": "grid",
            "images": [
              {
                "url": "https://images.unsplash.com/photo-1529390079861-591de354faf5?w=1200&q=85",
                "alt": "Children learning together; illustrative photograph",
                "caption": "A routine begins with listening."
              },
              {
                "url": "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=1800&q=85",
                "alt": "Hands gathered together; illustrative photograph",
                "caption": "Prototypes make questions tangible."
              },
              {
                "url": "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1600&q=85",
                "alt": "Friends gathered outdoors; illustrative photograph",
                "caption": "Feedback belongs in the room."
              },
              {
                "url": "/deessa-resources/IMG_8102.JPG",
                "alt": "Two children together near bookshelves; illustrative photograph",
                "caption": "Design follows real life."
              }
            ]
          }
        }
      ],
      "relatedProgramIds": []
    }
  },
  {
    "slug": "test-1000-families",
    "theme": "campaign",
    "document": {
      "schemaVersion": 1,
      "title": "1,000 Families Initiative",
      "shortDescription": "Let’s bring communication tools, practical guidance and a sense of belonging to 1,000 families across Nepal.",
      "eyebrow": "CAMPAIGNS / THE 1,000 FAMILIES INITIATIVE",
      "category": "campaign",
      "tags": [],
      "hero": {
        "title": "A little support.\nA world of",
        "description": "possibility.",
        "image": {
          "url": "/twins-together.jpg",
          "alt": "Two children sharing a moment outdoors; illustrative photograph"
        },
        "actions": [
          {
            "label": "Find your part in the story",
            "url": "#campaign-participate",
            "variant": "primary"
          },
          {
            "label": "Get to know the campaign",
            "url": "#campaign-why",
            "variant": "secondary"
          }
        ],
        "note": {
          "text": "Every family. Every possibility."
        },
        "editorial": {
          "captionLeft": "ONE SHARED GOAL.",
          "captionRight": "A thousand different stories."
        }
      },
      "seo": {
        "title": "1,000 Families Initiative — Test fixture",
        "description": "Let’s bring communication tools, practical guidance and a sense of belonging to 1,000 families across Nepal."
      },
      "sections": [
        {
          "id": "campaign-progress",
          "heading": "OUR SHARED GOAL",
          "intro": "Illustrative progress · September 2026",
          "description": "Connected with tools, learning and community.",
          "enabled": true,
          "content": {
            "type": "progress_tracker",
            "current": 820,
            "goal": 1000,
            "unit": "families"
          }
        },
        {
          "id": "campaign-why",
          "heading": "WHY THIS MATTERS",
          "intro": "No family should have to\n*figure it all out alone.*",
          "enabled": true,
          "content": {
            "type": "rich_text",
            "body": "<p>A child has something to say. A parent is looking for a way to understand. Sometimes, the first step is a simple picture board. Sometimes, it is meeting someone who listens.</p><p>This campaign brings those first steps closer to home, with practical support that families can use in their own routines.</p>"
          }
        },
        {
          "id": "campaign-promises",
          "heading": "What the campaign provides",
          "intro": "",
          "enabled": true,
          "content": {
            "type": "features",
            "layout": "grid",
            "features": [
              {
                "title": "Tools to express",
                "description": "Picture boards, visual routines and everyday resources that families can make their own.",
                "icon": "MessageCircle"
              },
              {
                "title": "Space to connect",
                "description": "Welcoming workshops where families learn alongside educators and local facilitators.",
                "icon": "Users"
              },
              {
                "title": "Support to grow",
                "description": "Follow-up conversations and community connections that continue beyond the first session.",
                "icon": "Heart"
              }
            ]
          }
        },
        {
          "id": "campaign-journey",
          "heading": "STEP BY STEP, TOGETHER",
          "intro": "A goal becomes\n*a journey.*",
          "description": "From the first conversation to the next community workshop, here is how the campaign moves forward.",
          "enabled": true,
          "content": {
            "type": "timeline",
            "items": [
              {
                "title": "Listen & connect",
                "description": "Start with families, local educators and the questions that matter in their everyday lives.",
                "status": "completed"
              },
              {
                "title": "Learn & make",
                "description": "Bring practical workshops and communication resources into more communities.",
                "status": "active"
              },
              {
                "title": "Keep showing up",
                "description": "Follow up with families and strengthen the local connections that help support last.",
                "status": "upcoming"
              }
            ]
          }
        },
        {
          "id": "campaign-stories",
          "heading": "A MOMENT FROM THE JOURNEY",
          "intro": "It starts with\n*“I understand.”*",
          "detailLabel": "Read the workshop story",
          "detailText": "Families explored visual choices through familiar activities: choosing a snack, planning a morning and asking for a break. The session ended with each family making a board to adapt at home, followed by a planned check-in with a facilitator.",
          "enabled": true,
          "content": {
            "type": "story",
            "quote": "“We left with something we could try together. That made the next step feel possible.”",
            "description": "At a community session, a parent tries a picture board for the first time. A small choice becomes a conversation, and a new possibility to take home.",
            "person": "Illustrative family story and quote",
            "image": {
              "url": "/deessa-resources/IMG_8102.JPG",
              "alt": "Two children together near bookshelves; illustrative photograph",
              "caption": "THE PEOPLE BEHIND THE PROGRESS"
            },
            "stats": []
          }
        },
        {
          "id": "campaign-reach",
          "heading": "MORE THAN A NUMBER",
          "intro": "Connection, in many forms.",
          "description": "Sample campaign reach · September 2026",
          "enabled": true,
          "content": {
            "type": "stats",
            "stats": [
              {
                "value": "820",
                "label": "families connected"
              },
              {
                "value": "156",
                "label": "learning sessions"
              },
              {
                "value": "25",
                "label": "districts reached"
              }
            ]
          }
        },
        {
          "id": "campaign-gallery",
          "heading": "A FEW MOMENTS ALONG THE WAY",
          "intro": "This is what\n*together looks like.*",
          "description": "Learning, listening and making space for each other. A glimpse of the everyday moments behind a shared goal.",
          "footnote": "Illustrative imagery for this design preview.",
          "enabled": true,
          "content": {
            "type": "gallery",
            "layout": "grid",
            "images": [
              {
                "url": "/twins-together.jpg",
                "alt": "Two children sharing a moment outdoors; illustrative photograph",
                "caption": "Connection begins with being together."
              },
              {
                "url": "/deessa-resources/IMG_8102.JPG",
                "alt": "Two children together near bookshelves; illustrative photograph",
                "caption": "Everyday moments. New possibilities."
              },
              {
                "url": "/twins-together.jpg",
                "alt": "Two children sharing a moment outdoors; illustrative photograph",
                "caption": "A little more confidence for tomorrow.",
                "focalPoint": "75% center"
              }
            ]
          }
        },
        {
          "id": "campaign-participate",
          "heading": "THERE IS A PLACE FOR YOU HERE",
          "intro": "",
          "enabled": true,
          "content": {
            "type": "cta",
            "title": "Bring what you can.\n*Be part of what’s next.*",
            "description": "Your time, your skills or a conversation can help this community grow.",
            "buttons": [
              {
                "label": "Explore ways to volunteer",
                "url": "/get-involved",
                "variant": "primary",
                "eyebrow": "01 / GIVE YOUR TIME",
                "title": "Help a session happen.",
                "description": "Support a workshop, translate a resource or connect us with your community."
              },
              {
                "label": "See a message to share",
                "url": "/contact",
                "variant": "primary",
                "eyebrow": "02 / START A CONVERSATION",
                "title": "Help the story travel.",
                "description": "Bring everyday communication into conversations with friends, schools and local groups."
              }
            ]
          }
        }
      ],
      "relatedProgramIds": []
    }
  }
]
$fixtures$::jsonb)
  loop
    doc := fixture->'document';
    -- Only the exact slug in this four-fixture payload is eligible for deletion.
    select existing.id into old_program_id from public.programs existing
      where existing.slug = fixture->>'slug' for update;
    if old_program_id is not null then
      -- Remove references to version snapshots before cascading the program delete.
      delete from public.program_publications where program_publications.program_id = old_program_id;
      delete from public.program_publish_requests where program_publish_requests.program_id = old_program_id;
      delete from public.programs where id = old_program_id;
    end if;

    insert into public.programs
      (slug, title, category, theme, eyebrow, short_description, tags, status, created_by, updated_by)
    values (
      fixture->>'slug', doc->>'title', doc->>'category', fixture->>'theme',
      doc->>'eyebrow', doc->>'shortDescription',
      array(select jsonb_array_elements_text(doc->'tags')), 'draft', admin_id, admin_id
    )
    returning id into program_id;

    insert into public.program_drafts
      (program_id, schema_version, hero, sections, seo_title, seo_description, revision, updated_by)
    values (
      program_id, 1, doc->'hero', doc->'sections',
      doc->'seo'->>'title', doc->'seo'->>'description', 1, admin_id
    );

    raise notice 'Ready: % (% sections), admin preview /admin/programs/%/preview',
      fixture->>'slug', jsonb_array_length(doc->'sections'), program_id;
  end loop;
end;
$seed$;
commit;

-- Open each draft from /admin/programs, edit/save, and use Preview.
-- /whatwedo/test-... becomes available only after publishing through the admin.
