import type { Artwork } from "./types"

// Imported from the shared Art Works by Deetya and Marissa folder.
const IMPORTED_ART_PHOTOS: Artwork[] = [
  {
    "id": "drive-1fEkcRbsVfqZpAlFDAjECmGhHczcziSUZ",
    "title": "Art by Deetya & Marissa 01",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "White dandelion flowers against a blue, green and yellow background, displayed in front of a stone wall.",
    "src": "/artWork/deetya-marissa/dsc06784.webp",
    "width": 1067,
    "height": 1600,
    "order": 0,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1xbtWfQsKg7Hn0l3GLVSlNB9YdCByQYFe",
    "title": "Art by Deetya & Marissa 02",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A dandelion painting propped on a wooden table in front of a stone wall.",
    "src": "/artWork/deetya-marissa/dsc06785.webp",
    "width": 1067,
    "height": 1600,
    "order": 1,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1BxkBcAJLYrcO6H0ED1PXAzSD2hngseo-",
    "title": "Art by Deetya & Marissa 03",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "Close-up of dandelion and orange sunset paintings arranged together.",
    "src": "/artWork/deetya-marissa/dsc06787.webp",
    "width": 1067,
    "height": 1600,
    "order": 2,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-14wDCMr6gn2bLUC5zKhVq6Hr-nyizyQlZ",
    "title": "Art by Deetya & Marissa 04",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A framed dandelion painting on a wooden table beside small flowers and ornaments.",
    "src": "/artWork/deetya-marissa/dsc06789.webp",
    "width": 1600,
    "height": 1067,
    "order": 3,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-18RGN3jlrB4_hN_ymAzW6TwdX6mjnLYKE",
    "title": "Art by Deetya & Marissa 05",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A blue and green starry night painting displayed on a wooden table.",
    "src": "/artWork/deetya-marissa/dsc06798.webp",
    "width": 1600,
    "height": 1067,
    "order": 4,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1bzyMRI6tfgZs9leJ7APZhVbJeNvGAH6f",
    "title": "Art by Deetya & Marissa 06",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A star-filled night sky painting beside a small vase and colourful ornaments.",
    "src": "/artWork/deetya-marissa/dsc06799.webp",
    "width": 1600,
    "height": 1067,
    "order": 5,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1ZvN8Mcdv-KRadBCi7BwmXSW5ikwvgW3N",
    "title": "Art by Deetya & Marissa 07",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A dotted painting of pink flamingos displayed on a wooden table.",
    "src": "/artWork/deetya-marissa/dsc06805.webp",
    "width": 1600,
    "height": 1067,
    "order": 6,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1rfcVTo7z2JwPQtcQBn38GkQecDIlfx7A",
    "title": "Art by Deetya & Marissa 08",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A white dandelion painting beside dried flowers on a wooden table.",
    "src": "/artWork/deetya-marissa/dsc06806.webp",
    "width": 1600,
    "height": 1067,
    "order": 7,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1G-P9DxlL8XSJ4hbSjEy4az4J1sTp2Ojn",
    "title": "Art by Deetya & Marissa 09",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A yellow and orange sunset painting with birds, displayed on a wooden table.",
    "src": "/artWork/deetya-marissa/dsc06808.webp",
    "width": 1600,
    "height": 1067,
    "order": 8,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1hov4qJUs655KLRs1fErf6P8_Pls-OEKH",
    "title": "Art by Deetya & Marissa 10",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A painting of birds flying above an orange sunset, tilted on a wooden table.",
    "src": "/artWork/deetya-marissa/dsc06810.webp",
    "width": 1600,
    "height": 1067,
    "order": 9,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1dNXjmnlraGiqWWIB6DdriwzsPoJZoaEP",
    "title": "Art by Deetya & Marissa 11",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "An orange sunset painting with flying birds and a pale sun above silhouetted trees.",
    "src": "/artWork/deetya-marissa/dsc06811.webp",
    "width": 1600,
    "height": 1067,
    "order": 10,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1vOCec1EX2W19hqMZn_3Vdt-FxrBCh-iY",
    "title": "Art by Deetya & Marissa 12",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A yellow sunset painting displayed beside flowers and small ornaments.",
    "src": "/artWork/deetya-marissa/dsc06812.webp",
    "width": 1600,
    "height": 1067,
    "order": 11,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1BMurazaLNYTCC1HRzFO9A0uSjDh9dpjq",
    "title": "Art by Deetya & Marissa 13",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A deer silhouette on a rocky hill against an orange sunset.",
    "src": "/artWork/deetya-marissa/dsc06813.webp",
    "width": 1600,
    "height": 1067,
    "order": 12,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1G1bS-d3zH1xvzCvFUzeFevzo5ZKS413p",
    "title": "Art by Deetya & Marissa 14",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "Two leaf paintings with black branches on yellow, orange and green backgrounds.",
    "src": "/artWork/deetya-marissa/dsc06815.webp",
    "width": 1600,
    "height": 1067,
    "order": 13,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-178k8O4YSJ-Kgr1XqoAqzDDKsJ6ar--TG",
    "title": "Art by Deetya & Marissa 15",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A small sunset painting with dark tree and bird silhouettes on a wooden table.",
    "src": "/artWork/deetya-marissa/dsc06816.webp",
    "width": 1600,
    "height": 1067,
    "order": 14,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1eh_8IQd_pkzqI2LRPF713RlGthWfF4ke",
    "title": "Art by Deetya & Marissa 16",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A yellow sunset painting photographed beside small flowers and colourful ornaments.",
    "src": "/artWork/deetya-marissa/dsc06817.webp",
    "width": 1600,
    "height": 1067,
    "order": 15,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1KyivnPvDciT20n-DH2V8EimobfMdi9F9",
    "title": "Art by Deetya & Marissa 17",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A blue and green night sky painting with white stars and dark tree silhouettes.",
    "src": "/artWork/deetya-marissa/dsc06818.webp",
    "width": 1600,
    "height": 1067,
    "order": 16,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1VGecn7HyflTh5LEvXT38uRSuPvxyqXl7",
    "title": "Art by Deetya & Marissa 18",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A crescent moon above a string of lights and dark trees in a blue night sky painting.",
    "src": "/artWork/deetya-marissa/dsc06819.webp",
    "width": 1600,
    "height": 1067,
    "order": 17,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1lQrIY61RBAvhHBLSloUOSmOWKNwA_zI8",
    "title": "Art by Deetya & Marissa 19",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A colourful cloud and rainbow painting displayed on a wooden table.",
    "src": "/artWork/deetya-marissa/dsc06820.webp",
    "width": 1600,
    "height": 1067,
    "order": 18,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1oFRovwn_kDWaKd4l6UurBu7m8wgnE0PA",
    "title": "Art by Deetya & Marissa 20",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A dotted pink flamingo painting beside flowers and small green ornaments.",
    "src": "/artWork/deetya-marissa/dsc06821.webp",
    "width": 1600,
    "height": 1067,
    "order": 19,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1yehXhzxOryIcJbdIFUJJOjYGlzSqC9Lu",
    "title": "Art by Deetya & Marissa 21",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A pink flamingo painting on a white sheet against a blue dotted background.",
    "src": "/artWork/deetya-marissa/dsc06822.webp",
    "width": 1600,
    "height": 1067,
    "order": 20,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1Fj6E-gClqkgo_cGCSKrkUoxdemdSGYKm",
    "title": "Art by Deetya & Marissa 22",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "Two flamingo paintings arranged at an angle on a wooden tabletop.",
    "src": "/artWork/deetya-marissa/dsc06823.webp",
    "width": 1600,
    "height": 1067,
    "order": 21,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1QZ9URJnWYD7d10R1bxxXuG_eAOmCm6Du",
    "title": "Art by Deetya & Marissa 23",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A pair of dotted pink flamingo paintings displayed beside flowers.",
    "src": "/artWork/deetya-marissa/dsc06824.webp",
    "width": 1600,
    "height": 1067,
    "order": 22,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1aSmrfxySH3eAvc-_7C7sm4SLajwOIcRF",
    "title": "Art by Deetya & Marissa 24",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A blue, pink and red sunset painting with small figures holding a heart.",
    "src": "/artWork/deetya-marissa/dsc06825.webp",
    "width": 1600,
    "height": 1067,
    "order": 23,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1j6quW6v2x1AOp6Bw18zROrGW_jwT1213",
    "title": "Art by Deetya & Marissa 25",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A painting with two small figures and a yellow heart beneath a colourful sky.",
    "src": "/artWork/deetya-marissa/dsc06826.webp",
    "width": 1600,
    "height": 1067,
    "order": 24,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1XB7OLzK2hc9HWn19Vfz32FJgqh3nR_Jx",
    "title": "Art by Deetya & Marissa 26",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A pink night sky painting with a crescent moon, string lights and tree silhouettes.",
    "src": "/artWork/deetya-marissa/dsc06827.webp",
    "width": 1600,
    "height": 1067,
    "order": 25,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1tuVurwT8layjgNWk1TMDGlV3w4GUWHq3",
    "title": "Art by Deetya & Marissa 27",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A colourful abstract painting photographed beside small green ornaments.",
    "src": "/artWork/deetya-marissa/dsc06828.webp",
    "width": 1600,
    "height": 1067,
    "order": 26,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1HZJZuYn-eH1QtjGIt3KVb90Ab7GZGBmD",
    "title": "Art by Deetya & Marissa 28",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A yellow flower canvas painting displayed on a wooden table.",
    "src": "/artWork/deetya-marissa/dsc06829.webp",
    "width": 1600,
    "height": 1067,
    "order": 27,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1VL8dH9RZRM86g9Z2MSWrXjKgN8Mkavzz",
    "title": "Art by Deetya & Marissa 29",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "An arrangement of flower, leaf, sunset and starry night paintings on a tabletop.",
    "src": "/artWork/deetya-marissa/dsc06830.webp",
    "width": 1600,
    "height": 1067,
    "order": 28,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1x7ExOthl0qtqwUxlSH4MDQjc9KA8X_BB",
    "title": "Art by Deetya & Marissa 30",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "Several colourful paintings arranged together, including leaves and a blue-green night sky.",
    "src": "/artWork/deetya-marissa/dsc06831.webp",
    "width": 1600,
    "height": 1067,
    "order": 29,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1ekJbKrC4s5mMpDTUSSCmiFhlFaJ9OKYU",
    "title": "Art by Deetya & Marissa 31",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A dandelion painting on a small easel beside a potted plant against a pale wall.",
    "src": "/artWork/deetya-marissa/dsc06834.webp",
    "width": 1600,
    "height": 1067,
    "order": 30,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1vYVKn0509n-xq1yG9sQ9tTUfIyRx1OTT",
    "title": "Art by Deetya & Marissa 32",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A green and yellow dandelion painting displayed on an easel with a small plant.",
    "src": "/artWork/deetya-marissa/dsc06836.webp",
    "width": 1600,
    "height": 1067,
    "order": 31,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1ebKQggSqjhnF9HD8O6UtuEjgthALbc6W",
    "title": "Art by Deetya & Marissa 33",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A close view of a dandelion painting on an easel against a pale wall.",
    "src": "/artWork/deetya-marissa/dsc06837.webp",
    "width": 1600,
    "height": 1067,
    "order": 32,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1mQgQPlQlU5TWwGBE_3xsqCZ_Y7RmKyaX",
    "title": "Art by Deetya & Marissa 34",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A yellow sunset painting on an easel beside a potted plant and orange ornaments.",
    "src": "/artWork/deetya-marissa/dsc06838.webp",
    "width": 1600,
    "height": 1067,
    "order": 33,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1Di9APgEKjTJsI507fTKJjG4kLVHCqvME",
    "title": "Art by Deetya & Marissa 35",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "An orange sunset and flying bird painting on an easel beside a green plant.",
    "src": "/artWork/deetya-marissa/dsc06839.webp",
    "width": 1600,
    "height": 1067,
    "order": 34,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1fW8IlRWGaF9MX7wD3rpGxu_V3TVtAXxW",
    "title": "Art by Deetya & Marissa 36",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A yellow flower canvas standing on a table beside small orange ornaments.",
    "src": "/artWork/deetya-marissa/dsc06840.webp",
    "width": 1600,
    "height": 1067,
    "order": 35,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-13KuYNuvmz9r4Mi3Ulf6EGgrqjKnjLKMX",
    "title": "Art by Deetya & Marissa 37",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A yellow and green floral canvas displayed against a pale wall.",
    "src": "/artWork/deetya-marissa/dsc06841.webp",
    "width": 1600,
    "height": 1067,
    "order": 36,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1qVuylgoLfwgUhEL8kibERshhPt-nDEMX",
    "title": "Art by Deetya & Marissa 38",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "Close-up of overlapping rainbow, dandelion and deer paintings.",
    "src": "/artWork/deetya-marissa/dsc06842.webp",
    "width": 1600,
    "height": 1067,
    "order": 37,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1VTkKQla0HpLP9KAjjPCPn6hdqot5OtFq",
    "title": "Art by Deetya & Marissa 39",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A dandelion painting arranged with a rainbow painting and other colourful art.",
    "src": "/artWork/deetya-marissa/dsc06843.webp",
    "width": 1600,
    "height": 1067,
    "order": 38,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-148w61kAkaxuHf9RSy9BwxhethTdB-Iyw",
    "title": "Art by Deetya & Marissa 40",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "Close-up of a deer painting against an orange and yellow sunset.",
    "src": "/artWork/deetya-marissa/dsc06844.webp",
    "width": 1600,
    "height": 1067,
    "order": 39,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1RDYQjsCBMx22imSGbWHj99BDCmwyYd0Z",
    "title": "Art by Deetya & Marissa 41",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A yellow sunset painting laid over other paintings on a wooden table.",
    "src": "/artWork/deetya-marissa/dsc06845.webp",
    "width": 1600,
    "height": 1067,
    "order": 40,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1iiA-LX1-UzQYeqs0d9l9PjA4iSd1IwHh",
    "title": "Art by Deetya & Marissa 42",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "An angled view of a yellow sunset painting with birds and dark tree silhouettes.",
    "src": "/artWork/deetya-marissa/dsc06846.webp",
    "width": 1600,
    "height": 1067,
    "order": 41,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1CyxMinuVVqKKgkaUMuTXD82FEKrP6yNk",
    "title": "Art by Deetya & Marissa 43",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "Close-up of yellow flowers and green stems in a textured canvas painting.",
    "src": "/artWork/deetya-marissa/dsc06847.webp",
    "width": 1600,
    "height": 1067,
    "order": 42,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1OW_vQ9tzjrz6MhNPH9woQRtp2RvjU1FP",
    "title": "Art by Deetya & Marissa 44",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A large pale sun above dark tree silhouettes in a yellow sunset painting.",
    "src": "/artWork/deetya-marissa/dsc06848.webp",
    "width": 1600,
    "height": 1066,
    "order": 43,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1ymAAM06XdJvxyUlws72UlXtR8VFHRPVf",
    "title": "Art by Deetya & Marissa 45",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "White dandelion flowers with green stems against a blue, green and yellow painted background.",
    "src": "/artWork/deetya-marissa/dsc06849.webp",
    "width": 1067,
    "height": 1600,
    "order": 44,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1dLoaYGh_hebO95s2S3YexzY22tXsyR0V",
    "title": "Art by Deetya & Marissa 46",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A dense starry sky above green hills and dark tree silhouettes.",
    "src": "/artWork/deetya-marissa/dsc06850.webp",
    "width": 1067,
    "height": 1600,
    "order": 45,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1nf2o50AmqZ0KeIZeEbtT5X4OJQMejHJ7",
    "title": "Art by Deetya & Marissa 47",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "A white crescent moon and string lights against a blue night sky above dark trees.",
    "src": "/artWork/deetya-marissa/dsc06851.webp",
    "width": 1600,
    "height": 1067,
    "order": 46,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1i89V__gV6vHKAIMaJIvS3cr0CTIOzzp3",
    "title": "Art by Deetya & Marissa 48",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "An angled close-up of a textured yellow and green floral canvas.",
    "src": "/artWork/deetya-marissa/dsc06852.webp",
    "width": 1600,
    "height": 1067,
    "order": 47,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  },
  {
    "id": "drive-1cDcTurw62ZpgLcGCa-jPJzT3SWjO9BLk",
    "title": "Art by Deetya & Marissa 49",
    "credit": "Deetya & Marissa",
    "description": null,
    "alt": "Yellow flowers and green leaves photographed at an angle on a textured canvas.",
    "src": "/artWork/deetya-marissa/dsc06853.webp",
    "width": 1600,
    "height": 1067,
    "order": 48,
    "isPublished": true,
    "isFeatured": false,
    "isUpload": false
  }
]

// One representative photograph per distinct artwork. Alternate angles,
// detail crops and group arrangements remain archived rather than repeated.
const CURATED_PHOTOS: Record<string, { title: string; existingSource?: string }> = {
  "/artWork/deetya-marissa/dsc06849.webp": { title: "Dandelion meadow", existingSource: "/artWork/dandelion-meadow.webp" },
  "/artWork/deetya-marissa/dsc06840.webp": { title: "Yellow flowers", existingSource: "/artWork/floral-canvas.webp" },
  "/artWork/deetya-marissa/dsc06851.webp": { title: "Moonlit lights", existingSource: "/artWork/moonlit-lights.webp" },
  "/artWork/deetya-marissa/dsc06813.webp": { title: "Deer at sunset", existingSource: "/artWork/deer-at-sunset.webp" },
  "/artWork/deetya-marissa/dsc06822.webp": { title: "Flamingo mosaic", existingSource: "/artWork/flamingo-mosaic.webp" },
  "/artWork/deetya-marissa/dsc06848.webp": { title: "Sunset birds", existingSource: "/artWork/sunset-birds.webp" },
  "/artWork/deetya-marissa/dsc06850.webp": { title: "Starry green night" },
  "/artWork/deetya-marissa/dsc06805.webp": { title: "Flamingo pair" },
  "/artWork/deetya-marissa/dsc06839.webp": { title: "Birds in an orange sky" },
  "/artWork/deetya-marissa/dsc06815.webp": { title: "Leaf studies" },
  "/artWork/deetya-marissa/dsc06817.webp": { title: "Sunset silhouettes" },
  "/artWork/deetya-marissa/dsc06820.webp": { title: "Rainbow and cloud" },
  "/artWork/deetya-marissa/dsc06825.webp": { title: "A heart beneath the sky" },
  "/artWork/deetya-marissa/dsc06827.webp": { title: "Pink moonlit evening" },
  "/artWork/deetya-marissa/dsc06828.webp": { title: "Colourful abstraction" },
}

export const SHARED_ARTWORKS: Artwork[] = IMPORTED_ART_PHOTOS
  .filter((artwork) => Boolean(CURATED_PHOTOS[artwork.src]))
  .map((artwork, order) => ({ ...artwork, title: CURATED_PHOTOS[artwork.src].title, order }))

/** Prefer published CMS entries over another photograph of the same piece. */
export function mergeSharedArtworks(published: Artwork[]): Artwork[] {
  const seen = new Set<string>()
  return [...published, ...SHARED_ARTWORKS].filter((artwork) => {
    const source = artwork.src.split("?")[0]
    const key = CURATED_PHOTOS[source]?.existingSource ?? source
    if (seen.has(key)) return false
    seen.add(key)
    return true
  })
}
